pull_request_rules:
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
  - name: request review for dependencies
    conditions: 
      - "label=dependencies"
      - "status-success=Codacy/PR Quality Review"
      - "status-success=CodeFactor"
      - "status-success=Travis CI - Branch"
      - "status-success=Travis CI - Pull Request"
      - "status-success=WIP"
      - "status-success=codebeat"
      - "status-success=codecov/patch"
      - "status-success=codecov/project"
      - "status-success=guardrails/scan"
      - "status-success=LGTM analysis: Java"
      - "base=master"
    actions:
      request_reviews:
        users: 
          - borettim
  - name : request milestone for dependencies
    conditions:
      - "label=dependencies"
      - "base=master"
      - "milestone~=^$"
      - "assignee~=^.+$"
    actions:
      comment:
        message: "Please add a milestone to this PR"
  - name : assign to borettim for dependencies
    conditions:
      - "label=dependencies"
      - "base=master"
      - "milestone~=^$"
      - "#assignee=0"
    actions:
      assign:
        users:
          - borettim
  - name: merge dependencies update when reviewed and validated
    conditions: 
      - "label=dependencies"
      - "#approved-reviews-by>=1"
      - "files=pom.xml"
      - "status-success=Codacy/PR Quality Review"
      - "status-success=CodeFactor"
      - "status-success=Travis CI - Branch"
      - "status-success=Travis CI - Pull Request"
      - "status-success=WIP"
      - "status-success=codebeat"
      - "status-success=codecov/patch"
      - "status-success=codecov/project"
      - "status-success=guardrails/scan"
      - "status-success=LGTM analysis: Java"
      - "base=master"
      - "milestone~=^.+$"
    actions:
      merge:
        method: merge
        strict: smart
