pull_request_rules:
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
  - name: request review for dependencies
    conditions:
      - "#approved-reviews-by=0"
      - "label=dependencies"
      - "status-success=Travis CI - Branch"
      - "status-success=Travis CI - Pull Request"
      - "status-success=WIP"
      - "status-success=guardrails/scan"
      - "status-success=Better Code Hub"
      - "status-success=AnyLint"
      - "base=master"
    actions:
      request_reviews:
        users:
          - boretti
  - name : request milestone for dependencies
    conditions:
      - "label=dependencies"
      - "base=master"
      - "milestone~=^$"
      - "assignee~=^.+$"
    actions:
      comment:
        message: "Please add a milestone to this PR"
  - name : assign to boretti for dependencies
    conditions:
      - "label=dependencies"
      - "base=master"
      - "milestone~=^$"
      - "#assignee=0"
    actions:
      assign:
        users:
          - boretti
  - name: merge dependencies update when reviewed and validated
    conditions:
      - "label=dependencies"
      - "#approved-reviews-by>=1"
      - "files=pom.xml"
      - "status-success=Travis CI - Branch"
      - "status-success=Travis CI - Pull Request"
      - "status-success=WIP"
      - "status-success=guardrails/scan"
      - "status-success=Better Code Hub"
      - "status-success=AnyLint"
      - "base=master"
      - "milestone~=^.+$"
    actions:
      merge:
        method: merge
        strict: smart
  - name: backport dependencies to version 1.2.X
    conditions:
      - base=master
      - label=dependencies
    actions:
      backport:
        branches:
          - versions/1.2.X
