if: NOT tag =~ ^ci/
language: java
notifications:
 slack:
  rooms:
   - "$slack_key#exceptions"
matrix:
 include:
  - os: linux
    jdk: oraclejdk9
  - os: linux
    jdk: openjdk10
  - os: linux
    jdk: openjdk11
jobs:
  allow_failures:
    - os: linux
      jdk: openjdk11
sudo: false
addons:
    apt:
      update: true
    sonarcloud:
      organization: "powerunit"
before_install:
 - git config --local user.name "powerunitci"
 - git config --local user.email "powerunitci@powerunit.ch"
 - cp .travis.settings.xml $HOME/.m2/settings.xml
 - if [[ "$TRAVIS_OS_NAME" = linux ]]; then sudo apt-get install jshon ; fi
 - if [[ "$TRAVIS_TAG" =~ powerunit-extensions-exceptions-[0-9].[0-9].[0-9] ]]; then echo $GPG_SECRET_KEYS | base64 --decode | gpg --import ; echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust ; fi
install:
- "mvn dependency:resolve dependency:resolve-plugins dependency:go-offline"
script:
- "mvn --log-file maven.log -e clean install"
after_failure:
- "curl -s https://report.ci/annotate.py | python - --name annotate$TRAVIS_OS_NAME$TRAVIS_JDK_VERSION --tool java --input maven.log"
- "curl -s https://report.ci/upload.py | python - --name upload$TRAVIS_OS_NAME$TRAVIS_JDK_VERSION --include='*.xml' --framework=junit"
after_success:
- "mvn jacoco:report coveralls:report -DrepoToken=${repoToken}"
- "bash <(curl -s https://codecov.io/bash) -c -Funit$TRAVIS_OS_NAME$TRAVIS_JDK_VERSION"
- "mvn org.apache.maven.plugins:maven-dependency-plugin:copy -Dartifact=com.codacy:codacy-coverage-reporter:6.0.0:jar:assembly -Dtransitive"
- "mvn jacoco:merge -Djacoco.destFile=target/jacoco-aggregate.exe"
- "mvn jacoco:report -Djacoco.dataFile=target/jacoco-aggregate.exe"
- "curl -s https://report.ci/annotate.py | python - --name annotate$TRAVIS_OS_NAME$TRAVIS_JDK_VERSION --tool java --input maven.log"
- "curl -s https://report.ci/upload.py | python - --name upload$TRAVIS_OS_NAME$TRAVIS_JDK_VERSION --include='*.xml' --framework=junit"
- "(cd target/dependency && java -jar codacy-coverage-reporter-6.0.0-assembly.jar report -l Java -r ../site/jacoco/jacoco.xml)"
- if [[ "$TRAVIS_JDK_VERSION" = openjdk10 ]]; then git fetch --unshallow ; mvn sonar:sonar -Dsonar.projectKey=powerunit_powerunit-extensions-exceptions ; fi
- if [[ "$TRAVIS_JDK_VERSION" = openjdk10 ]]; then rm -f target/classes/module-info.class; mvn site ; fi
- mkdir -p target/announcement ; mvn org.apache.maven.plugins:maven-changes-plugin:announcement-generate || echo 'Nothing for the moment' > target/announcement/announcement.vm ; export RELEASE_NOTES=$(jshon -s "$(cat target/announcement/announcement.vm)")
deploy:
  - provider: script
    script: git rev-list --tags=ci/master* --before=`date --date yesterday +%Y-%M-%d`|xargs -n 1 git describe --abbrev=0 --tags | grep "ci/$TRAVIS_BRANCH" | uniq | xargs -n 1 git push --delete origin ; git tag -m "Create ci tag [ci skip]" -f "ci/$TRAVIS_BRANCH/$TRAVIS_BUILD_NUMBER"
    skip-cleanup: true
    on:
      branch: master
      tags: false
      condition: $TRAVIS_JDK_VERSION = openjdk10
  - provider: pages
    skip-cleanup: true
    keep-history: false
    github-token: $GITHUB_TOKEN
    local-dir: target/site
    on:
      branch: master
      condition: $TRAVIS_JDK_VERSION = openjdk10
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: target/*.jar
    skip_cleanup: true
    prerelease: true
    draft: false
    body: "$RELEASE_NOTES"
    on:
      branch: master
      tags: false
      condition: $TRAVIS_JDK_VERSION = openjdk10
  - provider: script
    script: mvn deploy -DskipTests=true -B
    skip-cleanup: true
    on:
      branch: master
      tags: false
      condition: $TRAVIS_JDK_VERSION = openjdk10
#  - provider: script
#    script: mvn deploy -DskipTests=true -B -U -Psign,release
#    skip-cleanup: true
#    on:
#      tags: true
#      condition: $TRAVIS_JDK_VERSION = openjdk10 && "$TRAVIS_TAG" =~ powerunit-extensions-exceptions-[0-9].[0-9].[0-9]
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: target/*.jar
    skip_cleanup: true
    prerelease: false
    draft: false
    body: "$RELEASE_NOTES"
    on:
      tags: true
      condition: $TRAVIS_JDK_VERSION = openjdk10 && "$TRAVIS_TAG" =~ powerunit-extensions-exceptions-[0-9].[0-9].[0-9]
